services:
  - type: web
    name: sajid-portfolio-backend
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: FRONTEND_ORIGIN
        value: https://sajid-portfolio.netlify.app
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    rootDir: backend
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 1
